# Demo Code to explain constants, variables and placeholders

In [1]:
# Import the TensorFlow Library
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf

In [10]:
# Execute the graph/evaluate the node
sess.run(init_op)

In [26]:
# Placeholders

In [14]:
#Not initialized to any value - unlike Constants and variables
a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)

In [28]:
#We cannot create a variable like this
#2=tf.Variable(tf.float32)
#3=tf.constant(tf.float32)

In [27]:
c=a+b

In [22]:
# Create a session
sess=tf.Session()

In [28]:
result=sess.run(c,feed_dict={a:10,b:20})

In [33]:
print(result)

300.0


In [31]:
d=a*c

In [32]:
result=sess.run(d,feed_dict={a:10,b:20})

In [32]:
#sess.run(b)

In [35]:
avalues=[1,2,3]
bvalues=[4,5,6]

In [36]:
result=sess.run(c,feed_dict={a:avalues,b:bvalues})

In [37]:
print(result)

[5. 7. 9.]


In [18]:
sess.run(b,feed_dict={a:[1,2,3,4]})

array([2., 4., 6., 8.], dtype=float32)

In [38]:
#d=a*c ... why are we feeding a and b instead of a and c ?
result=sess.run(d,feed_dict={a:avalues,b:bvalues})

In [39]:
print(result)

[ 5. 14. 27.]


In [20]:
result=sess.run(b,feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [21]:
sess.close()

In [43]:
#sess.run(var1)