## Initializing Variables, creating Placeholders

In [1]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf

In [2]:
# Variables

In [3]:
# How to create variable of shape [3,4] and initialize it to zero

In [4]:
var1=tf.Variable([[0,0,0,0],[0,0,0,0],[0,0,0,0]])

In [5]:
init_op=tf.global_variables_initializer()

In [6]:
sess=tf.Session()

In [7]:
sess.run(init_op)

In [8]:
sess.run(var1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
# tf.zeros and tf.ones

In [10]:
myvar=tf.Variable(tf.zeros([3,4]))

In [11]:
init_op=tf.global_variables_initializer()
sess.run(init_op)

In [12]:
sess.run(myvar)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [13]:
myvar1=tf.Variable(tf.ones([5,3,2,3]))

In [14]:
init_op=tf.global_variables_initializer()
sess.run(init_op)

In [15]:
sess.run(myvar1)

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)

In [16]:
# Initializes to random values around mean value
W4=tf.Variable(tf.truncated_normal([5,3],mean=0, stddev=.2))

In [17]:
init_op=tf.global_variables_initializer()
sess.run(init_op)

In [18]:
sess.run(W4)

array([[-0.16017132,  0.28356573, -0.2418197 ],
       [-0.15277494, -0.1740115 ,  0.04644255],
       [-0.21295165,  0.10303569,  0.15257736],
       [ 0.10598458, -0.13409103,  0.17753866],
       [-0.1316521 , -0.09802619,  0.080877  ]], dtype=float32)

In [19]:
# Placeholder Creation

In [20]:
a=tf.placeholder(tf.float32)

In [21]:
# Define placeholder of specific shape
b=tf.placeholder(tf.float32,[5,3])

In [22]:
c=tf.placeholder(tf.float32,[None,6])

In [23]:
d=tf.placeholder(tf.float32,[None,3])

In [24]:
y=tf.Variable([[1,2,3,4,5,6]])

In [25]:
init_op=tf.global_variables_initializer()
sess.run(init_op)

In [26]:
# Placeholders

In [27]:
yresult=sess.run(y)

In [28]:
sess.run(a,feed_dict={a:yresult})

array([[1., 2., 3., 4., 5., 6.]], dtype=float32)

In [29]:
# b has shape [5,3]
b

<tf.Tensor 'Placeholder_1:0' shape=(5, 3) dtype=float32>

In [31]:
# Not allowed unlike Variable
#sess.run(b,feed_dict={b:yresult})

In [32]:
# c has a shape [None,1]
c

<tf.Tensor 'Placeholder_2:0' shape=(?, 6) dtype=float32>

In [33]:
sess.run(c,feed_dict={c:yresult})

array([[1., 2., 3., 4., 5., 6.]], dtype=float32)

In [34]:
wresult=sess.run(W4)

In [36]:
W4

<tf.Variable 'Variable_3:0' shape=(5, 3) dtype=float32_ref>

In [35]:
sess.run(b,feed_dict={b:wresult})

array([[ 0.14802928, -0.18800022,  0.05383767],
       [-0.04588545,  0.11861277, -0.09140097],
       [ 0.05189474, -0.1556653 , -0.07449915],
       [ 0.18799494,  0.36108303,  0.30115098],
       [ 0.12026121,  0.34840506,  0.05615086]], dtype=float32)