## Initializing Variables, creating Placeholders

In [1]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf

In [2]:
# Variables

In [3]:
# tf.zeros and tf.ones

In [48]:
myvar=tf.Variable(tf.zeros([3,4]))

In [57]:
myvar1=tf.Variable(tf.ones([5,3,2,3]))

In [39]:
y=tf.Variable([[1,2,3,4,5,6]])

In [50]:
ynew=tf.Variable(tf.zeros([6,1]))

In [51]:
# Initializes to random values around mean value
W4=tf.Variable(tf.truncated_normal([5,3],mean=0, stddev=.2))

In [58]:
init_op=tf.global_variables_initializer()

In [59]:
sess=tf.Session()

In [60]:
sess.run(init_op)

In [55]:
sess.run(myvar)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [61]:
sess.run(myvar1)

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)

In [62]:
sess.run(W4)

array([[-0.19628847, -0.39245686,  0.21280213],
       [ 0.03510818, -0.15518586,  0.07737398],
       [ 0.04517667,  0.18071716, -0.26668948],
       [-0.16623639,  0.38436913, -0.33823618],
       [-0.16920245,  0.10554659, -0.2544766 ]], dtype=float32)

In [19]:
# Placeholder Creation

In [20]:
a=tf.placeholder(tf.float32)

In [21]:
# Define placeholder of specific shape
b=tf.placeholder(tf.float32,[5,3])

In [22]:
c=tf.placeholder(tf.float32,[None,6])

In [23]:
d=tf.placeholder(tf.float32,[None,3])

In [26]:
# Placeholders

In [27]:
yresult=sess.run(y)

In [64]:
sess.run(a,feed_dict={a:yresult})

array([[1., 2., 3., 4., 5., 6.]], dtype=float32)

In [65]:
# b has shape [5,3]
b

<tf.Tensor 'Placeholder_1:0' shape=(5, 3) dtype=float32>

In [66]:
# Not allowed unlike Variable
#sess.run(b,feed_dict={b:yresult})

In [67]:
# c has a shape [None,1]
c

<tf.Tensor 'Placeholder_2:0' shape=(?, 6) dtype=float32>

In [68]:
sess.run(c,feed_dict={c:yresult})

array([[1., 2., 3., 4., 5., 6.]], dtype=float32)

In [69]:
wresult=sess.run(W4)

In [70]:
W4

<tf.Variable 'Variable_13:0' shape=(5, 3) dtype=float32_ref>

In [71]:
sess.run(b,feed_dict={b:wresult})

array([[-0.19628847, -0.39245686,  0.21280213],
       [ 0.03510818, -0.15518586,  0.07737398],
       [ 0.04517667,  0.18071716, -0.26668948],
       [-0.16623639,  0.38436913, -0.33823618],
       [-0.16920245,  0.10554659, -0.2544766 ]], dtype=float32)